version: "3.3"

services:

  jenkins:
    image: jenkins/jenkins:latest
    ports:
    - "9080:8080"
    volumes:
      - home_compose:/var/jenkins_home
    restart: unless-stopped

  mails:
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
    - "7025:8025" # mailhog's web app (think test instance of gmail)

volumes:
  home_compose:
