pipeline {
  agent any
  stages {
    stage ('Build') {
      steps {
        echo 'Building project.....'
      }
    }
    stage ('Deploy') {
      steps {
        echo 'Deploying project.....'
      }
    }
    stage ('Test') {
      steps {
        echo 'Tesing project.....'
      }
    }
    stage ('Release') {
      steps {
        echo 'Releasing project.....'
      }
    }
    stage ('Post Release') {
      steps {
        echo 'Executing post release checks...'
      }
    }
  }
}
