pipeline {
  agent any
  stages {
    stage ('Build') {
      when {
        expression {
          (BRANCH_NAME == 'develop' || BRANCH_NAME == 'master') && CODE_CHANGES == true
        }
      }
      steps {
        echo 'Building project.....'
      }
    }
    stage ('Deploy') {
      steps {
        echo 'Deploying project.....'
      }
    }
    stage ('Test') {
      steps {
        echo 'Tesing project.....'
      }
    }
    stage ('Release') {
      steps {
        echo 'Releasing project.....'
      }
    }
    stage ('Post Release') {
      steps {
        echo 'Executing post release checks...'
      }
    }
  }
}
